# Use an official Python runtime
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# --- THE MAGIC PART ---
# 1. Copy ONLY the requirements first
COPY requirements-frontend.txt .

# 2. Install dependencies (including gdown for model weights)
# Since requirements-frontend.txt hasn't changed, Docker will use the CACHE for this layer!
RUN pip install --no-cache-dir -r requirements-frontend.txt 


# 4. Copy the rest of the code
# This layer will be rebuilt, but it's super fast (just copying files)
COPY *.py /app
# ----------------------

EXPOSE 7860


CMD ["python", "frontend.py"]